package:
  name: htrc-feature-reader
  version: "1.50"

source:
  fn: htrc-feature-reader-1.50.tar.gz
  url: https://files.pythonhosted.org/packages/58/d0/d783e1587ad8721b901170a95b777c4e07155f6b498388bc54d35dc63f28/htrc-feature-reader-1.50.tar.gz
  md5: 0f1a573232aae290f4f26f02b5d460b1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - htrc-feature-reader = htrc-feature-reader:main
    #
    # Would create an entry point called htrc-feature-reader that calls htrc-feature-reader.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - pytest-runner
    - setuptools
    - six
    - pandas
    - numpy
    - pysolr
    - ujson

  run:
    - python
    - six
    - pandas
    - numpy
    - pysolr
    - ujson

test:
  # Python imports
  imports:
    - htrc_features

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/organisciak/htrc-feature-reader
  license: University of Illinois/NCSA Open Source License
  summary: 'Library for working with the HTRC Extracted Features dataset'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
