package:
  name: pysolr
  version: "3.5.0"

source:
  fn: pysolr-3.5.0.tar.gz
  url: https://files.pythonhosted.org/packages/b4/ab/079c1ed3d562753d9e5c86db4452e24412ca08f019400829e1f4116485e4/pysolr-3.5.0.tar.gz
  md5: e6ca3fa5be45d7452a04c1c316f8b883
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysolr = pysolr:main
    #
    # Would create an entry point called pysolr that calls pysolr.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.0

  run:
    - python
    - requests >=2.0

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/toastdriven/pysolr/
  license: BSD License
  summary: 'Lightweight python wrapper for Apache Solr.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
