package:
  name: pytest-runner
  version: "2.9"

source:
  fn: pytest-runner-2.9.tar.gz
  url: https://files.pythonhosted.org/packages/11/d4/c335ddf94463e451109e3494e909765c3e5205787b772e3b25ee8601b86a/pytest-runner-2.9.tar.gz
  md5: 2212a2e34404b0960b2fdc2c469247b2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest-runner = pytest-runner:main
    #
    # Would create an entry point called pytest-runner that calls pytest-runner.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools_scm
    - setuptools

  run:
    - python
    - setuptools

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pytest-dev/pytest-runner
  license: MIT License
  summary: 'Invoke py.test as distutils command with dependency resolution'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
